/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 032c856ebed10a58b7535cdcb624303a)
interface __BaseEnv_Env {
	REPORTS: R2Bucket;
	CASE_CREATION_RATE_LIMITER: RateLimit;
	MUTATION_RATE_LIMITER: RateLimit;
	GRANT_TTL_SECONDS: "600";
	MAX_UPLOAD_BYTES: "6291456";
	PUBLIC_ORIGIN: "https://preflight-report-intake.leoli-082000.workers.dev";
	RETENTION_DAYS: "14";
	DAILY_REPORT_QUOTA: DurableObjectNamespace<import("./src/index").DailyReportQuota>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DailyReportQuota";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GRANT_TTL_SECONDS" | "MAX_UPLOAD_BYTES" | "PUBLIC_ORIGIN" | "RETENTION_DAYS">> {}
}
