/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ed32c07480d82f4026ff248d37d2f4f0)
interface __BaseEnv_Env {
	REPORTS: R2Bucket;
	GRANT_TTL_SECONDS: "600";
	MAX_UPLOAD_BYTES: "6291456";
	PUBLIC_ORIGIN: "https://reports.preflight.invalid";
	RETENTION_DAYS: "14";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GRANT_TTL_SECONDS" | "MAX_UPLOAD_BYTES" | "PUBLIC_ORIGIN" | "RETENTION_DAYS">> {}
}
