package dev.starsector.preflight.agent;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Generates a class shaped exactly like the game's rule expression class.
 *
 * <p>Written with ASM rather than as Java source for two reasons. The class the game ships is named
 * {@code com.fs.starfarer.campaign.rules.super}, which the JVM accepts and {@code javac} does not;
 * and the plan matches on the exact instruction shape of {@code getCommandClass}, so a fixture that
 * merely behaves the same would not exercise it. Nothing here is copied from the game -- it is
 * written from the disassembly of a method whose Java form is in {@link RuleCommandClassCachePlan}'s
 * documentation, and the generated bytecode is this repository's own.
 *
 * <p>The generated class can be defined and run, so the tests check what the rewrite <em>does</em>
 * and not only what it looks like.
 */
final class RuleCommandLookupFixture {
    static final String MEMO_FIELD = "ø00000";
    static final String PACKAGES_FIELD = "ö00000";
    static final String LOADER_METHOD = "loader";

    private RuleCommandLookupFixture() {
    }

    static byte[] vanilla() {
        return generate(1, 1, "java/lang/Exception");
    }

    /**
     * @param forNameCalls more than one makes the method ambiguous and must be declined
     * @param handlers more than one handler is a shape this plan has not reviewed
     * @param caught the handler's exception type; vanilla catches exactly {@code Exception}
     */
    static byte[] generate(int forNameCalls, int handlers, String caught) {
        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        writer.visit(Opcodes.V17, Opcodes.ACC_PUBLIC,
                RuleCommandClassCachePlan.TARGET_CLASS, null, "java/lang/Object", null);
        writer.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                MEMO_FIELD, "Ljava/util/Map;", null, null).visitEnd();
        writer.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                PACKAGES_FIELD, "Ljava/util/List;", null, null).visitEnd();

        // A static accessor returning a class loader, standing in for ScriptStore's. The plan clones
        // whichever two instructions vanilla uses here rather than naming them, so any static
        // accessor with a reference return type followed by getParent() is the shape it accepts.
        MethodVisitor loader = writer.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                LOADER_METHOD, "()Ljava/lang/ClassLoader;", null, null);
        loader.visitCode();
        loader.visitFieldInsn(Opcodes.GETSTATIC,
                "dev/starsector/preflight/agent/RuleCommandLoaderProbe", "LOADER",
                "Ljava/lang/ClassLoader;");
        loader.visitInsn(Opcodes.ARETURN);
        loader.visitMaxs(0, 0);
        loader.visitEnd();

        writeLookup(writer, forNameCalls, handlers, caught);
        writer.visitEnd();
        return writer.toByteArray();
    }

    private static void writeLookup(
            ClassWriter writer, int forNameCalls, int handlers, String caught) {
        MethodVisitor method = writer.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                RuleCommandClassCachePlan.LOOKUP_METHOD,
                RuleCommandClassCachePlan.LOOKUP_DESCRIPTOR, null, null);
        method.visitCode();

        Label walk = new Label();
        Label loopBody = new Label();
        Label loopTest = new Label();
        Label exhausted = new Label();

        // if (memo.containsKey(name)) return (String) memo.get(name);
        method.visitFieldInsn(Opcodes.GETSTATIC,
                RuleCommandClassCachePlan.TARGET_CLASS, MEMO_FIELD, "Ljava/util/Map;");
        method.visitVarInsn(Opcodes.ALOAD, 0);
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/Map", "containsKey",
                "(Ljava/lang/Object;)Z", true);
        method.visitJumpInsn(Opcodes.IFEQ, walk);
        method.visitFieldInsn(Opcodes.GETSTATIC,
                RuleCommandClassCachePlan.TARGET_CLASS, MEMO_FIELD, "Ljava/util/Map;");
        method.visitVarInsn(Opcodes.ALOAD, 0);
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/Map", "get",
                "(Ljava/lang/Object;)Ljava/lang/Object;", true);
        method.visitTypeInsn(Opcodes.CHECKCAST, "java/lang/String");
        method.visitInsn(Opcodes.ARETURN);

        // String tried = ""; Iterator it = ruleCommandPackages.iterator();
        method.visitLabel(walk);
        method.visitLdcInsn("");
        method.visitVarInsn(Opcodes.ASTORE, 1);
        method.visitFieldInsn(Opcodes.GETSTATIC,
                RuleCommandClassCachePlan.TARGET_CLASS, PACKAGES_FIELD, "Ljava/util/List;");
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/List", "iterator",
                "()Ljava/util/Iterator;", true);
        method.visitVarInsn(Opcodes.ASTORE, 3);
        method.visitJumpInsn(Opcodes.GOTO, loopTest);

        method.visitLabel(loopBody);
        method.visitVarInsn(Opcodes.ALOAD, 3);
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/Iterator", "next",
                "()Ljava/lang/Object;", true);
        method.visitTypeInsn(Opcodes.CHECKCAST, "java/lang/String");
        method.visitVarInsn(Opcodes.ASTORE, 2);

        // tried = tried + pkg + "\n";
        method.visitTypeInsn(Opcodes.NEW, "java/lang/StringBuilder");
        method.visitInsn(Opcodes.DUP);
        method.visitVarInsn(Opcodes.ALOAD, 1);
        method.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/String", "valueOf",
                "(Ljava/lang/Object;)Ljava/lang/String;", false);
        method.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/StringBuilder", "<init>",
                "(Ljava/lang/String;)V", false);
        method.visitVarInsn(Opcodes.ALOAD, 2);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitLdcInsn("\n");
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "toString",
                "()Ljava/lang/String;", false);
        method.visitVarInsn(Opcodes.ASTORE, 1);

        // String fqn = pkg + "." + name;
        method.visitTypeInsn(Opcodes.NEW, "java/lang/StringBuilder");
        method.visitInsn(Opcodes.DUP);
        method.visitVarInsn(Opcodes.ALOAD, 2);
        method.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/String", "valueOf",
                "(Ljava/lang/Object;)Ljava/lang/String;", false);
        method.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/StringBuilder", "<init>",
                "(Ljava/lang/String;)V", false);
        method.visitLdcInsn(".");
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitVarInsn(Opcodes.ALOAD, 0);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "toString",
                "()Ljava/lang/String;", false);
        method.visitVarInsn(Opcodes.ASTORE, 4);

        Label tryStart = new Label();
        Label tryEnd = new Label();
        Label handler = new Label();
        Label resolved = new Label();
        for (int index = 0; index < handlers; index++) {
            method.visitTryCatchBlock(tryStart, tryEnd, handler, caught);
        }

        method.visitLabel(tryStart);
        for (int index = 0; index < forNameCalls; index++) {
            method.visitVarInsn(Opcodes.ALOAD, 4);
            method.visitInsn(Opcodes.ICONST_0);
            method.visitMethodInsn(Opcodes.INVOKESTATIC, RuleCommandClassCachePlan.TARGET_CLASS,
                    LOADER_METHOD, "()Ljava/lang/ClassLoader;", false);
            method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/ClassLoader", "getParent",
                    "()Ljava/lang/ClassLoader;", false);
            method.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Class", "forName",
                    "(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class;", false);
            method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/Class", "newInstance",
                    "()Ljava/lang/Object;", false);
            method.visitInsn(Opcodes.POP);
        }
        method.visitLabel(tryEnd);
        method.visitJumpInsn(Opcodes.GOTO, resolved);

        method.visitLabel(handler);
        method.visitVarInsn(Opcodes.ASTORE, 5);
        method.visitJumpInsn(Opcodes.GOTO, loopTest);

        // memo.put(name, fqn); return fqn;
        method.visitLabel(resolved);
        method.visitFieldInsn(Opcodes.GETSTATIC,
                RuleCommandClassCachePlan.TARGET_CLASS, MEMO_FIELD, "Ljava/util/Map;");
        method.visitVarInsn(Opcodes.ALOAD, 0);
        method.visitVarInsn(Opcodes.ALOAD, 4);
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/Map", "put",
                "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", true);
        method.visitInsn(Opcodes.POP);
        method.visitVarInsn(Opcodes.ALOAD, 4);
        method.visitInsn(Opcodes.ARETURN);

        method.visitLabel(loopTest);
        method.visitVarInsn(Opcodes.ALOAD, 3);
        method.visitMethodInsn(Opcodes.INVOKEINTERFACE, "java/util/Iterator", "hasNext",
                "()Z", true);
        method.visitJumpInsn(Opcodes.IFNE, loopBody);

        method.visitLabel(exhausted);
        method.visitTypeInsn(Opcodes.NEW, "java/lang/RuntimeException");
        method.visitInsn(Opcodes.DUP);
        method.visitTypeInsn(Opcodes.NEW, "java/lang/StringBuilder");
        method.visitInsn(Opcodes.DUP);
        method.visitLdcInsn("Command [");
        method.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/StringBuilder", "<init>",
                "(Ljava/lang/String;)V", false);
        method.visitVarInsn(Opcodes.ALOAD, 0);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitLdcInsn("] not found in packages:\n");
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitVarInsn(Opcodes.ALOAD, 1);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "append",
                "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        method.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/StringBuilder", "toString",
                "()Ljava/lang/String;", false);
        method.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/RuntimeException", "<init>",
                "(Ljava/lang/String;)V", false);
        method.visitInsn(Opcodes.ATHROW);

        method.visitMaxs(0, 0);
        method.visitEnd();
    }
}
