from pathlib import Path

path = Path("docs/release-gate-closeout.md")
text = path.read_text()
start_marker = "## #678 — current cross-process desktop race\n"
end_marker = "## Exact candidate preparation\n"
assert text.count(start_marker) == 1, "expected one #678 closeout section"
assert text.count(end_marker) == 1, "expected one Exact candidate preparation section"
start = text.index(start_marker)
end = text.index(end_marker, start)
replacement = '''## #678 — packaged desktop single-instance contract\n\nResolved on main by #795. The selected beta correctness contract is **one packaged Preflight desktop process per user/session**; focus/reveal/handoff IPC is optional later product polish, not a release gate.\n\n### Implemented lifetime guard\n\nThe cross-process guard is acquired in the tiny native `main.rs` entrypoint before the Tauri application and process-local `OperationCoordinator` exist.\n\n- Unix prefers the validated owner-private runtime directory and otherwise creates/validates an owner-private `0700` fallback before opening the stable lock name with `O_NOFOLLOW` and holding an exclusive `flock`.\n- Windows holds a session-local named kernel mutex.\n- A normal second invocation gets a bounded two-second collision grace and then exits cleanly without creating a second normal Tauri lifetime or operation coordinator.\n- Tauri updater restart uses the same grace because the replacement process may start before the old process has exited; the child becomes primary as soon as the old lifetime releases the guard.\n- Windows collision handles are closed before retry so a waiting replacement cannot accidentally keep the old mutex object alive itself.\n- Guard-acquisition errors fail closed with a bounded diagnostic.\n\nThe Java `OperationLease` continues to serialize Java-backed CLI mutations. The native single-instance guard closes the separate packaged-Desktop lifetime gap for update/export/benchmark/game/preparation ownership.\n\n### Installed-package evidence\n\nRun against the exact installed candidate on Linux, Windows, and macOS:\n\n1. start Preflight and wait for the first native host; launch a second invocation and require the second process to exit within the bounded collision grace without creating a second normal app lifetime;\n2. repeat while preparation/game ownership is active and require exactly one admitted desktop coordinator and one owned game/preparation lifetime;\n3. repeat during diagnostics export and update operations; the second invocation must still exit without admitting independent native operation state;\n4. exercise updater restart overlap and require the replacement process to acquire the guard immediately after the old lifetime releases it;\n5. on Windows, burst at least eight simultaneous invocations during first-instance startup and require exactly one primary while every non-primary invocation exits within the bounded grace; **no focus/handoff assertion is part of this contract**;\n6. repeat the burst after install, update, and rollback;\n7. after the primary exits and after uninstall/removal, verify no helper process or live singleton ownership remains.\n\nA failure to maintain one admitted normal desktop lifetime blocks the candidate. Window focus/reveal behavior does not.\n\n'''
text = text[:start] + replacement + text[end:]
path.write_text(text)
