package dev.starsector.preflight.core;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

/** One checksummed, content-deduplicated set of exact Janino complete-map results. */
public final class GeneratedBytecodePack {
    private static final byte[] MAGIC = {'S', 'P', 'J', 'P'};
    public static final int FORMAT_VERSION = 1;
    private static final int CHECKSUM_BYTES = 32;
    private static final int MAX_REQUESTS = 10_000;
    private static final int MAX_MEMBERSHIPS = 10_000_000;
    private static final int MAX_FILE_BYTES = 544 * 1024 * 1024;
    private static final int MAX_NAME_BYTES = GeneratedBytecodeBundle.MAX_CLASS_NAME_CHARS * 4;

    private final String contextKeySha256;
    private final Map<String, byte[]> classes;
    private final Map<String, List<String>> requests;
    private final long uniqueBytecodeBytes;
    private final long expandedBytecodeBytes;

    private GeneratedBytecodePack(
            String contextKeySha256,
            Map<String, byte[]> suppliedClasses,
            Map<String, List<String>> suppliedRequests) {
        Hashes.decodeSha256(contextKeySha256);
        this.contextKeySha256 = contextKeySha256.toLowerCase(Locale.ROOT);
        Objects.requireNonNull(suppliedClasses, "classes");
        Objects.requireNonNull(suppliedRequests, "requests");
        if (suppliedClasses.isEmpty() || suppliedRequests.isEmpty()) {
            throw new IllegalArgumentException("Generated bytecode pack requires classes and requests");
        }
        if (suppliedClasses.size() > GeneratedBytecodeBundle.MAX_CLASS_COUNT
                || suppliedRequests.size() > MAX_REQUESTS) {
            throw new IllegalArgumentException("Generated bytecode pack exceeds its entry limit");
        }

        TreeMap<String, byte[]> orderedClasses = new TreeMap<>();
        long uniqueBytes = 0L;
        for (Map.Entry<String, byte[]> entry : suppliedClasses.entrySet()) {
            String name = canonicalName(entry.getKey());
            byte[] bytecode = Objects.requireNonNull(entry.getValue(), "bytecode for " + name).clone();
            if (bytecode.length < 10 || bytecode.length > GeneratedBytecodeBundle.MAX_CLASS_BYTES) {
                throw new IllegalArgumentException("Generated class " + name + " has invalid bytecode length");
            }
            try {
                String actual = ClassFileIdentity.binaryName(bytecode);
                if (!name.equals(actual)) {
                    throw new IllegalArgumentException(
                            "Generated class map key " + name + " differs from classfile identity " + actual);
                }
            } catch (IOException error) {
                throw new IllegalArgumentException("Generated class " + name + " is not a valid classfile", error);
            }
            if (orderedClasses.put(name, bytecode) != null) {
                throw new IllegalArgumentException("Duplicate generated class " + name);
            }
            uniqueBytes = Math.addExact(uniqueBytes, bytecode.length);
            if (uniqueBytes > GeneratedBytecodeBundle.MAX_TOTAL_CLASS_BYTES) {
                throw new IllegalArgumentException("Generated bytecode pack exceeds its byte limit");
            }
        }

        TreeMap<String, List<String>> orderedRequests = new TreeMap<>();
        long memberships = 0L;
        long expandedBytes = 0L;
        for (Map.Entry<String, List<String>> entry : suppliedRequests.entrySet()) {
            String request = canonicalName(entry.getKey());
            List<String> members = new ArrayList<>();
            String previous = null;
            for (String supplied : Objects.requireNonNull(entry.getValue(), "members for " + request)) {
                String member = canonicalName(supplied);
                byte[] bytecode = orderedClasses.get(member);
                if (bytecode == null || (previous != null && previous.compareTo(member) >= 0)) {
                    throw new IllegalArgumentException("Generated bytecode request has invalid members: " + request);
                }
                members.add(member);
                previous = member;
                memberships = Math.addExact(memberships, 1L);
                expandedBytes = Math.addExact(expandedBytes, bytecode.length);
            }
            if (members.isEmpty() || !members.contains(request) || memberships > MAX_MEMBERSHIPS) {
                throw new IllegalArgumentException("Generated bytecode request is incomplete: " + request);
            }
            if (orderedRequests.put(request, List.copyOf(members)) != null) {
                throw new IllegalArgumentException("Duplicate generated bytecode request " + request);
            }
        }
        LinkedHashMap<String, byte[]> stableClasses = new LinkedHashMap<>();
        orderedClasses.forEach(stableClasses::put);
        this.classes = Collections.unmodifiableMap(stableClasses);
        this.requests = Collections.unmodifiableMap(new LinkedHashMap<>(orderedRequests));
        this.uniqueBytecodeBytes = uniqueBytes;
        this.expandedBytecodeBytes = expandedBytes;
    }

    public String contextKeySha256() {
        return contextKeySha256;
    }

    public int classCount() {
        return classes.size();
    }

    public int requestCount() {
        return requests.size();
    }

    public long uniqueBytecodeBytes() {
        return uniqueBytecodeBytes;
    }

    public long expandedBytecodeBytes() {
        return expandedBytecodeBytes;
    }

    /** Returns an independent mutable map and byte arrays, matching the existing bundle contract. */
    public Map<String, byte[]> classesFor(String requestedClassName) {
        List<String> members = requests.get(requestedClassName);
        if (members == null) return null;
        LinkedHashMap<String, byte[]> result = new LinkedHashMap<>();
        for (String member : members) result.put(member, classes.get(member).clone());
        return result;
    }

    /** Whether this pack makes one older per-request bundle byte-for-byte redundant. */
    public boolean exactlyContains(GeneratedBytecodeBundle bundle) {
        Objects.requireNonNull(bundle, "bundle");
        if (!contextKeySha256.equals(bundle.contextKeySha256())) return false;
        List<String> members = requests.get(bundle.requestedClassName());
        Map<String, byte[]> bundled = bundle.internalClasses();
        if (members == null || members.size() != bundled.size()) return false;
        for (String member : members) {
            byte[] packed = classes.get(member);
            byte[] separate = bundled.get(member);
            if (packed == null || separate == null || !Arrays.equals(packed, separate)) return false;
        }
        return true;
    }

    /** Removes older per-request bundles only when this checked pack contains the exact bytes. */
    public ReleaseResult releaseExactBundles(Path cacheRoot) {
        Objects.requireNonNull(cacheRoot, "cacheRoot");
        long releasedBytes = 0;
        int releasedBundles = 0;
        int retainedBundles = 0;
        for (String requestedClassName : requests.keySet()) {
            GeneratedBytecodeCache.Lookup lookup = GeneratedBytecodeCache.lookup(
                    cacheRoot, contextKeySha256, requestedClassName);
            if (lookup.status() != GeneratedBytecodeCache.Status.HIT
                    || !exactlyContains(lookup.bundle())) {
                retainedBundles++;
                continue;
            }
            try {
                long bytes = Files.size(lookup.path());
                if (Files.deleteIfExists(lookup.path())) {
                    releasedBundles++;
                    releasedBytes = Math.addExact(releasedBytes, bytes);
                }
            } catch (IOException | RuntimeException error) {
                retainedBundles++;
            }
        }
        return new ReleaseResult(releasedBundles, releasedBytes, retainedBundles);
    }

    public record ReleaseResult(long releasedBundles, long releasedBytes, long retainedBundles) {
    }

    public static Path path(Path cacheRoot, String contextKeySha256) {
        Hashes.decodeSha256(contextKeySha256);
        String context = contextKeySha256.toLowerCase(Locale.ROOT);
        Path root = cacheRoot.toAbsolutePath().normalize();
        Path target = GeneratedBytecodeCache.root(cacheRoot)
                .resolve(context.substring(0, 2)).resolve(context)
                .resolve("pack-v" + FORMAT_VERSION + ".spjp").normalize();
        if (!target.startsWith(root)) throw new IllegalArgumentException("Generated bytecode path escaped cache root");
        return target;
    }

    public static GeneratedBytecodePack read(Path source) throws IOException {
        return read(source, MAX_FILE_BYTES);
    }

    static GeneratedBytecodePack read(Path source, int maximumBytes) throws IOException {
        validateReadLimit(maximumBytes);
        Path absolute = source.toAbsolutePath().normalize();
        if (Files.isSymbolicLink(absolute)
                || !Files.isRegularFile(absolute, LinkOption.NOFOLLOW_LINKS)) {
            throw new IOException("Generated bytecode pack is not a regular file: " + absolute);
        }
        long size = Files.size(absolute);
        if (size < minimumFileBytes() || size > maximumBytes) {
            throw new IOException("Generated bytecode pack has an invalid size: " + size);
        }
        try (InputStream input = Files.newInputStream(absolute, StandardOpenOption.READ)) {
            return read(input, maximumBytes, absolute.toString());
        }
    }

    static GeneratedBytecodePack read(InputStream input, int maximumBytes, String sourceLabel) throws IOException {
        validateReadLimit(maximumBytes);
        byte[] bytes = input.readNBytes(maximumBytes + 1);
        if (bytes.length > maximumBytes) {
            throw new IOException(
                    "Generated bytecode pack exceeds the " + maximumBytes + " byte safety limit: " + sourceLabel);
        }
        if (bytes.length < minimumFileBytes()) {
            throw new IOException("Generated bytecode pack has an invalid size: " + bytes.length);
        }
        return fromBytes(bytes);
    }

    public static void write(Path target, GeneratedBytecodePack pack) throws IOException {
        Path absolute = target.toAbsolutePath().normalize();
        Path parent = absolute.getParent();
        if (parent != null) Files.createDirectories(parent);
        byte[] bytes = toBytes(pack);
        Path temporary = absolute.resolveSibling(
                absolute.getFileName() + ".tmp-" + ProcessHandle.current().pid() + "-" + System.nanoTime());
        boolean moved = false;
        try {
            try (FileChannel channel = FileChannel.open(
                    temporary, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)) {
                ByteBuffer buffer = ByteBuffer.wrap(bytes);
                while (buffer.hasRemaining()) channel.write(buffer);
                channel.force(true);
            }
            AtomicPublish.replace(temporary, absolute);
            moved = true;
        } finally {
            if (!moved) Files.deleteIfExists(temporary);
        }
    }

    public static byte[] toBytes(GeneratedBytecodePack pack) throws IOException {
        byte[] payload = encodePayload(pack);
        long total = minimumFileBytes() + payload.length;
        if (total > MAX_FILE_BYTES) throw new IOException("Generated bytecode pack exceeds its file limit");
        ByteArrayOutputStream bytes = new ByteArrayOutputStream((int) total);
        try (DataOutputStream output = new DataOutputStream(bytes)) {
            output.write(MAGIC);
            output.writeInt(FORMAT_VERSION);
            output.writeInt(payload.length);
            output.write(payload);
            output.write(Hashes.sha256Bytes(payload));
        }
        return bytes.toByteArray();
    }

    public static GeneratedBytecodePack fromBytes(byte[] bytes) throws IOException {
        if (bytes.length < minimumFileBytes() || bytes.length > MAX_FILE_BYTES) {
            throw new IOException("Generated bytecode pack has an invalid size");
        }
        try (DataInputStream input = new DataInputStream(new ByteArrayInputStream(bytes))) {
            if (!Arrays.equals(MAGIC, input.readNBytes(MAGIC.length))) {
                throw new IOException("Generated bytecode pack magic is invalid");
            }
            if (input.readInt() != FORMAT_VERSION) throw new IOException("Unsupported generated bytecode pack");
            int payloadLength = input.readInt();
            if (payloadLength < 40 || minimumFileBytes() + (long) payloadLength != bytes.length) {
                throw new IOException("Generated bytecode pack payload length is invalid");
            }
            byte[] payload = input.readNBytes(payloadLength);
            byte[] checksum = input.readNBytes(CHECKSUM_BYTES);
            if (payload.length != payloadLength || checksum.length != CHECKSUM_BYTES) throw new EOFException();
            if (!MessageDigest.isEqual(checksum, Hashes.sha256Bytes(payload))) {
                throw new IOException("Generated bytecode pack checksum mismatch");
            }
            return decodePayload(payload);
        } catch (IllegalArgumentException | ArithmeticException error) {
            throw new IOException("Generated bytecode pack contains invalid data: " + error.getMessage(), error);
        }
    }

    private static byte[] encodePayload(GeneratedBytecodePack pack) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        try (DataOutputStream output = new DataOutputStream(bytes)) {
            output.write(Hashes.decodeSha256(pack.contextKeySha256));
            output.writeInt(pack.classes.size());
            LinkedHashMap<String, Integer> indexes = new LinkedHashMap<>();
            int index = 0;
            for (Map.Entry<String, byte[]> entry : pack.classes.entrySet()) {
                indexes.put(entry.getKey(), index++);
                writeString(output, entry.getKey());
                output.writeInt(entry.getValue().length);
                output.write(Hashes.sha256Bytes(entry.getValue()));
                output.write(entry.getValue());
            }
            output.writeInt(pack.requests.size());
            for (Map.Entry<String, List<String>> entry : pack.requests.entrySet()) {
                writeString(output, entry.getKey());
                output.writeInt(entry.getValue().size());
                for (String member : entry.getValue()) output.writeInt(indexes.get(member));
            }
        }
        return bytes.toByteArray();
    }

    private static GeneratedBytecodePack decodePayload(byte[] payload) throws IOException {
        try (DataInputStream input = new DataInputStream(new ByteArrayInputStream(payload))) {
            byte[] context = input.readNBytes(32);
            if (context.length != 32) throw new EOFException();
            int classCount = input.readInt();
            if (classCount < 1 || classCount > GeneratedBytecodeBundle.MAX_CLASS_COUNT) {
                throw new IOException("Generated bytecode pack class count is invalid");
            }
            List<String> names = new ArrayList<>(classCount);
            LinkedHashMap<String, byte[]> classes = new LinkedHashMap<>();
            for (int i = 0; i < classCount; i++) {
                String name = readString(input);
                int length = input.readInt();
                if (length < 10 || length > GeneratedBytecodeBundle.MAX_CLASS_BYTES) {
                    throw new IOException("Generated bytecode pack class length is invalid");
                }
                byte[] expected = input.readNBytes(32);
                byte[] bytecode = input.readNBytes(length);
                if (expected.length != 32 || bytecode.length != length
                        || !MessageDigest.isEqual(expected, Hashes.sha256Bytes(bytecode))) {
                    throw new IOException("Generated bytecode pack class checksum mismatch");
                }
                names.add(name);
                if (classes.put(name, bytecode) != null) throw new IOException("Duplicate generated class");
            }
            int requestCount = input.readInt();
            if (requestCount < 1 || requestCount > MAX_REQUESTS) {
                throw new IOException("Generated bytecode pack request count is invalid");
            }
            LinkedHashMap<String, List<String>> requests = new LinkedHashMap<>();
            long memberships = 0L;
            for (int i = 0; i < requestCount; i++) {
                String request = readString(input);
                int count = input.readInt();
                if (count < 1 || count > classCount) throw new IOException("Invalid request membership count");
                List<String> members = new ArrayList<>(count);
                for (int j = 0; j < count; j++) {
                    int member = input.readInt();
                    if (member < 0 || member >= names.size()) throw new IOException("Invalid class reference");
                    members.add(names.get(member));
                }
                memberships += count;
                if (memberships > MAX_MEMBERSHIPS || requests.put(request, members) != null) {
                    throw new IOException("Invalid generated bytecode request table");
                }
            }
            if (input.available() != 0) throw new IOException("Generated bytecode pack has trailing data");
            return new GeneratedBytecodePack(HexFormatHolder.HEX.formatHex(context), classes, requests);
        }
    }

    private static String canonicalName(String value) {
        Objects.requireNonNull(value, "className");
        if (value.isEmpty() || value.length() > GeneratedBytecodeBundle.MAX_CLASS_NAME_CHARS
                || value.startsWith(".") || value.endsWith(".") || value.contains("..")) {
            throw new IllegalArgumentException("Generated class name is not canonical: " + value);
        }
        return value;
    }

    private static void writeString(DataOutputStream output, String value) throws IOException {
        if (!StandardCharsets.UTF_8.newEncoder().canEncode(value)) {
            throw new IOException("Generated class name cannot be encoded as UTF-8");
        }
        byte[] bytes = value.getBytes(StandardCharsets.UTF_8);
        if (bytes.length < 1 || bytes.length > MAX_NAME_BYTES) throw new IOException("Invalid class name length");
        output.writeInt(bytes.length);
        output.write(bytes);
    }

    private static String readString(DataInputStream input) throws IOException {
        int length = input.readInt();
        if (length < 1 || length > MAX_NAME_BYTES) throw new IOException("Invalid class name length");
        byte[] bytes = input.readNBytes(length);
        if (bytes.length != length) throw new EOFException();
        String value = new String(bytes, StandardCharsets.UTF_8);
        if (!Arrays.equals(bytes, value.getBytes(StandardCharsets.UTF_8))) throw new IOException("Invalid UTF-8");
        return value;
    }

    private static void validateReadLimit(int maximumBytes) {
        if (maximumBytes < minimumFileBytes() || maximumBytes > MAX_FILE_BYTES) {
            throw new IllegalArgumentException("Generated bytecode pack read limit is invalid: " + maximumBytes);
        }
    }

    private static long minimumFileBytes() {
        return MAGIC.length + Integer.BYTES * 2L + CHECKSUM_BYTES;
    }

    private static final class HexFormatHolder {
        private static final java.util.HexFormat HEX = java.util.HexFormat.of();
    }

    /** Accumulates validated complete maps and deduplicates identical class bytes by binary name. */
    public static final class Builder {
        private final String context;
        private final Map<String, byte[]> classes = new LinkedHashMap<>();
        private final Map<String, List<String>> requests = new LinkedHashMap<>();
        private boolean conflicted;
        private boolean changed;

        public Builder(String contextKeySha256) {
            Hashes.decodeSha256(contextKeySha256);
            context = contextKeySha256.toLowerCase(Locale.ROOT);
        }

        public Builder(GeneratedBytecodePack existing) {
            Objects.requireNonNull(existing, "existing");
            context = existing.contextKeySha256;
            existing.classes.forEach((name, bytes) -> classes.put(name, bytes.clone()));
            existing.requests.forEach((request, members) -> requests.put(request, members));
        }

        public synchronized boolean record(String request, Map<String, byte[]> completeMap) {
            if (conflicted || completeMap == null || !completeMap.containsKey(request)) return false;
            TreeMap<String, byte[]> ordered = new TreeMap<>(completeMap);
            for (Map.Entry<String, byte[]> entry : ordered.entrySet()) {
                byte[] prior = classes.get(entry.getKey());
                if (prior != null && !Arrays.equals(prior, entry.getValue())) {
                    conflicted = true;
                    return false;
                }
            }
            for (Map.Entry<String, byte[]> entry : ordered.entrySet()) {
                if (!classes.containsKey(entry.getKey())) {
                    classes.put(entry.getKey(), entry.getValue().clone());
                    changed = true;
                }
            }
            List<String> members = List.copyOf(ordered.keySet());
            List<String> prior = requests.putIfAbsent(request, members);
            if (prior == null) changed = true;
            if (prior != null && !prior.equals(members)) conflicted = true;
            return !conflicted;
        }

        public synchronized GeneratedBytecodePack build() {
            if (conflicted || requests.isEmpty() || !changed) return null;
            return new GeneratedBytecodePack(context, classes, requests);
        }
    }
}
