package dev.starsector.preflight.cli;

import dev.starsector.preflight.core.GeneratedBytecodeBundle;
import dev.starsector.preflight.core.GeneratedBytecodeBundleIO;
import dev.starsector.preflight.core.GeneratedBytecodeCache;
import dev.starsector.preflight.core.GeneratedBytecodePack;
import dev.starsector.preflight.core.ClasspathCacheDirectories;
import dev.starsector.preflight.core.PreparedAudioManifest;
import dev.starsector.preflight.core.PreparedAudioManifestIO;
import dev.starsector.preflight.core.PreparedAudioCache;
import dev.starsector.preflight.core.PreparedTexturePackIO;
import dev.starsector.preflight.core.PreparedTextureIO;
import dev.starsector.preflight.core.ResourceIndexIO;
import dev.starsector.preflight.core.SpecStoreCacheDirectories;
import dev.starsector.preflight.core.TextureManifest;
import dev.starsector.preflight.core.TextureManifestIO;
import java.io.IOException;
import java.nio.file.DirectoryNotEmptyException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Works out which cache files no surviving profile can reach.
 *
 * <p>Artifacts fall into two kinds and only one of them is safe to delete by name. Resource
 * indexes, texture manifests and spec-store artifacts carry their profile's fingerprint or identity
 * in the filename, so a file belonging to a discarded profile is simply a file whose name is not in
 * the survivor set. Texture and prepared-audio blobs are not like that: they are content-addressed
 * and <b>shared</b>, so the same blob is routinely referenced by several profiles and its name says
 * nothing about who needs it. Deleting one is only safe after reading every surviving manifest and
 * confirming none of them points at it.
 *
 * <p>That asymmetry drives the safety rule here: <b>a manifest that cannot be read aborts the whole
 * plan.</b> An unreadable survivor means an incomplete reachable set, and an incomplete reachable
 * set means deleting blobs a live profile still needs -- which would not fail loudly, it would fail
 * on the next launch as a cache miss on a texture that was supposed to be prepared. Refusing to
 * plan is the only correct response.
 */
final class CachePrune {
    /** Spec-store corpora, and the extension each writes. */
    private static final List<String> SPEC_STORE_EXTENSIONS =
            List.of(".spvj", ".spwj", ".sppj", ".sphj", ".sprc", ".sprk", ".sprt", ".spmr");

    private CachePrune() {
    }

    /**
     * Plans a prune that keeps exactly {@code survivors}.
     *
     * @param keepIdentities spec-store identities the surviving profiles resolve to, or empty to
     *     leave every spec-store artifact alone rather than guess at which ones are live
     */
    static Plan plan(PreflightHome home, Set<String> survivors, Set<String> keepIdentities)
            throws IOException {
        return plan(home, survivors, keepIdentities, Set.of());
    }

    /**
     * Plans a prune including exact generated-bytecode contexts.
     *
     * @param keepJaninoContexts compiler-context keys that remain reachable, or empty to leave all
     *     generated bytecode alone rather than guess
     */
    static Plan plan(
            PreflightHome home,
            Set<String> survivors,
            Set<String> keepIdentities,
            Set<String> keepJaninoContexts) throws IOException {
        Path cache = home.cache().toAbsolutePath().normalize();
        List<Removal> removals = new ArrayList<>();
        List<String> refusals = new ArrayList<>();
        try {
            CacheDeletionBoundary.requireSafeTree(cache);
        } catch (IOException unsafe) {
            refusals.add("cache deletion boundary could not be verified (" + message(unsafe) + ")");
            return new Plan(cache, List.of(), List.copyOf(refusals), 0, 0);
        }

        removals.addAll(byFingerprint(ResourceIndexIO.directory(cache), ".spfi", survivors));
        removals.addAll(byFingerprint(TextureManifestIO.directory(cache), ".spfm", survivors));
        removals.addAll(byFingerprint(MinimalPreparationMarker.directory(cache), ".spmn", survivors));
        removals.addAll(byFingerprint(PreparedTexturePackIO.directory(cache), ".spfp", survivors));
        removals.addAll(byFingerprint(PreparedTexturePackIO.directory(cache), ".spfo", survivors));
        removals.addAll(byFingerprint(
                PreparedAudioCache.manifestDirectory(cache), ".spam", survivors));
        removals.addAll(byFingerprint(
                ClasspathCacheDirectories.profiles(cache), ".spfc", survivors));

        Set<String> reachable = new HashSet<>();
        for (String survivor : survivors) {
            Path manifest = TextureManifestIO.directory(cache).resolve(survivor + ".spfm");
            if (!Files.isRegularFile(manifest, LinkOption.NOFOLLOW_LINKS)) {
                // A survivor with no manifest simply contributes no blobs; it is not an error,
                // because a profile can be indexed without having had its textures prepared.
                continue;
            }
            try {
                TextureManifest read = TextureManifestIO.read(manifest);
                for (TextureManifest.Entry entry : read.entries().values()) {
                    reachable.add(entry.blobRelativePath());
                }
            } catch (Exception unreadable) {
                refusals.add("manifest for surviving profile " + survivor.substring(0, 16)
                        + " could not be read (" + message(unreadable) + "), so the set of blobs it"
                        + " still needs is unknown");
            }
        }

        List<Removal> blobs = refusals.isEmpty()
                ? unreachableBlobs(cache, reachable)
                : List.of();
        removals.addAll(blobs);

        Set<String> reachableAudio = new HashSet<>();
        for (String survivor : survivors) {
            Path manifest = PreparedAudioCache.manifestDirectory(cache)
                    .resolve(survivor + ".spam");
            if (!Files.isRegularFile(manifest, LinkOption.NOFOLLOW_LINKS)) {
                continue;
            }
            try {
                PreparedAudioManifest read = PreparedAudioManifestIO.read(manifest);
                if (!survivor.equals(read.profileFingerprintSha256())) {
                    throw new IOException("profile fingerprint does not match its filename");
                }
                for (PreparedAudioManifest.Entry entry : read.entries().values()) {
                    if (entry.policy().cacheEligible()) {
                        reachableAudio.add(entry.cacheKeySha256());
                    }
                }
            } catch (Exception unreadable) {
                refusals.add("prepared-audio manifest for surviving profile "
                        + survivor.substring(0, 16) + " could not be read ("
                        + message(unreadable) + "), so the set of PCM blobs it still needs is unknown");
            }
        }
        List<Removal> audioBlobs = refusals.isEmpty()
                ? unreachableAudioBlobs(cache, reachableAudio)
                : List.of();
        removals.addAll(audioBlobs);

        if (!keepIdentities.isEmpty()) {
            removals.addAll(specStore(cache, keepIdentities));
        }
        if (!keepJaninoContexts.isEmpty()) {
            removals.addAll(generatedBytecode(cache, keepJaninoContexts));
        }

        removals.sort(Comparator.comparingLong(Removal::bytes).reversed());
        return new Plan(
                cache,
                List.copyOf(removals),
                List.copyOf(refusals),
                reachable.size(),
                reachableAudio.size());
    }

    private static List<Removal> byFingerprint(Path directory, String extension, Set<String> keep)
            throws IOException {
        List<Removal> removals = new ArrayList<>();
        if (!Files.isDirectory(directory, LinkOption.NOFOLLOW_LINKS)) {
            return removals;
        }
        try (var stream = Files.list(directory)) {
            for (Path file : stream
                    .filter(path -> Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)).toList()) {
                String name = file.getFileName().toString();
                if (!name.endsWith(extension)) {
                    continue;
                }
                String fingerprint = name.substring(0, name.length() - extension.length());
                if (fingerprint.matches("[0-9a-f]{64}") && !keep.contains(fingerprint)) {
                    removals.add(new Removal(file, Files.size(file), "profile " + short16(fingerprint)));
                }
            }
        }
        return removals;
    }

    /**
     * Removes unreachable compiler contexts and per-request bundles exactly represented by the
     * surviving context's deduplicated pack. An unreadable pack or bundle is retained.
     */
    private static List<Removal> generatedBytecode(Path cache, Set<String> keepContexts)
            throws IOException {
        Path root = GeneratedBytecodeCache.root(cache);
        List<Removal> removals = new ArrayList<>();
        if (!Files.isDirectory(root, LinkOption.NOFOLLOW_LINKS)) return removals;

        try (var shards = Files.list(root)) {
            for (Path shard : shards
                    .filter(path -> Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)).toList()) {
                try (var contexts = Files.list(shard)) {
                    for (Path directory : contexts
                            .filter(path -> Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS))
                            .toList()) {
                        String context = directory.getFileName().toString();
                        if (!context.matches("[0-9a-f]{64}")) continue;
                        if (!keepContexts.contains(context)) {
                            collectRegularFiles(directory, removals,
                                    "stale generated-bytecode context " + short16(context));
                            continue;
                        }
                        redundantBundles(directory, context, removals);
                    }
                }
            }
        }
        return removals;
    }

    private static void redundantBundles(
            Path directory, String context, List<Removal> removals) {
        Path packPath = directory.resolve("pack-v1.spjp");
        final GeneratedBytecodePack pack;
        try {
            pack = GeneratedBytecodePack.read(packPath);
            if (!context.equals(pack.contextKeySha256())) return;
        } catch (Exception unreadable) {
            return;
        }
        try (var files = Files.list(directory)) {
            for (Path file : files
                    .filter(path -> Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)).toList()) {
                if (!file.getFileName().toString().endsWith(".spjb")) continue;
                try {
                    GeneratedBytecodeBundle bundle = GeneratedBytecodeBundleIO.read(file);
                    if (pack.exactlyContains(bundle)) {
                        removals.add(new Removal(
                                file, Files.size(file), "redundant generated-bytecode bundle"));
                    }
                } catch (Exception unreadable) {
                    // An artifact we cannot prove redundant stays.
                }
            }
        } catch (IOException unreadableDirectory) {
            // A context that changed during planning stays partially or wholly untouched.
        }
    }

    private static void collectRegularFiles(
            Path directory, List<Removal> removals, String reason) throws IOException {
        Files.walkFileTree(directory, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attributes) {
                if (attributes.isRegularFile()) {
                    removals.add(new Removal(file, attributes.size(), reason));
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private static List<Removal> unreachableBlobs(Path cache, Set<String> reachable)
            throws IOException {
        Path blobs = PreparedTextureIO.cacheDirectory(cache);
        List<Removal> removals = new ArrayList<>();
        if (!Files.isDirectory(blobs, LinkOption.NOFOLLOW_LINKS)) {
            return removals;
        }
        Files.walkFileTree(blobs, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attributes) {
                if (!attributes.isRegularFile()) {
                    return FileVisitResult.CONTINUE;
                }
                String relative = cache.relativize(file).toString().replace('\\', '/');
                if (!reachable.contains(relative)) {
                    removals.add(new Removal(file, attributes.size(), "unreferenced blob"));
                }
                return FileVisitResult.CONTINUE;
            }
        });
        return removals;
    }

    private static List<Removal> unreachableAudioBlobs(Path cache, Set<String> reachable)
            throws IOException {
        Path root = PreparedAudioCache.root(cache);
        List<Removal> removals = new ArrayList<>();
        if (!Files.isDirectory(root, LinkOption.NOFOLLOW_LINKS)) {
            return removals;
        }
        Files.walkFileTree(root, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attributes) {
                if (!attributes.isRegularFile()) {
                    return FileVisitResult.CONTINUE;
                }
                String name = file.getFileName().toString();
                if (!name.endsWith(".spau")) {
                    return FileVisitResult.CONTINUE;
                }
                String key = name.substring(0, name.length() - ".spau".length());
                if (key.matches("[0-9a-f]{64}") && !reachable.contains(key)) {
                    removals.add(new Removal(
                            file, attributes.size(), "unreferenced prepared-audio blob"));
                }
                return FileVisitResult.CONTINUE;
            }
        });
        return removals;
    }

    private static List<Removal> specStore(Path cache, Set<String> keepIdentities)
            throws IOException {
        List<Removal> removals = new ArrayList<>();
        Set<Path> activeStores = Set.of(
                SpecStoreCacheDirectories.variantJson(cache),
                SpecStoreCacheDirectories.weaponJson(cache),
                SpecStoreCacheDirectories.projectileJson(cache),
                SpecStoreCacheDirectories.hullJson(cache),
                SpecStoreCacheDirectories.rulesCsv(cache),
                SpecStoreCacheDirectories.ruleCommandClasses(cache),
                SpecStoreCacheDirectories.mergedReads(cache));
        for (Path corpus : activeStores) {
            if (!Files.isDirectory(corpus, LinkOption.NOFOLLOW_LINKS)) {
                continue;
            }
            try (var files = Files.list(corpus)) {
                for (Path file : files
                        .filter(path -> Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)).toList()) {
                    String name = file.getFileName().toString();
                    String identity = SPEC_STORE_EXTENSIONS.stream()
                            .filter(name::endsWith)
                            .findFirst()
                            .map(extension ->
                                    name.substring(0, name.length() - extension.length()))
                            .orElse(null);
                    if (identity != null
                            && identity.matches("[0-9a-f]{64}")
                            && !keepIdentities.contains(identity)) {
                        removals.add(new Removal(
                                file, Files.size(file), "stale " + corpus.getFileName()));
                    }
                }
            }
        }
        return removals;
    }

    static long apply(Plan plan) throws IOException {
        if (!plan.safe()) {
            throw new IOException("Refusing to apply an unsafe cache-prune plan");
        }
        Path cache = plan.cacheRoot();
        if (cache == null) {
            throw new IOException("Refusing to apply a cache-prune plan without an owned cache root");
        }
        CacheDeletionBoundary.requireSafeTree(cache);
        long freed = 0;
        Set<Path> parents = new LinkedHashSet<>();
        for (Removal removal : plan.removals()) {
            if (CacheDeletionBoundary.deleteOwnedRegularFile(cache, removal.path())) {
                freed = Math.addExact(freed, removal.bytes());
            }
            Path parent = removal.path().getParent();
            if (parent != null) {
                parents.add(parent);
            }
        }
        for (Path parent : parents) {
            // A blob shard that emptied out is noise, not cache. Non-empty directories throw and
            // are left alone, while every other failure remains visible to the caller.
            try {
                CacheDeletionBoundary.deleteOwnedEmptyDirectory(cache, parent);
            } catch (DirectoryNotEmptyException stillPopulated) {
                // Intentionally ignored.
            }
        }
        return freed;
    }

    private static String short16(String fingerprint) {
        return fingerprint.substring(0, 16);
    }

    private static String message(Throwable error) {
        String text = error.getMessage();
        return text == null || text.isBlank() ? error.getClass().getSimpleName() : text;
    }

    record Removal(Path path, long bytes, String reason) {
    }

    record Plan(
            Path cacheRoot,
            List<Removal> removals,
            List<String> refusals,
            int reachableBlobs,
            int reachableAudioBlobs) {
        Plan(
                List<Removal> removals,
                List<String> refusals,
                int reachableBlobs,
                int reachableAudioBlobs) {
            this(null, removals, refusals, reachableBlobs, reachableAudioBlobs);
        }

        long bytes() {
            return removals.stream().mapToLong(Removal::bytes).sum();
        }

        boolean safe() {
            return refusals.isEmpty();
        }
    }
}
